### ISSUE TITLE
Prompt hangs intermittently

### ISSUE THREAD

**Issue by jaraco** [JeremySkinner/posh-hg#31]
I continue to run into the same issue [reported in this Superuser question](http://superuser.com/questions/700786/powershell-periodically-hangs-after-any-command) which implicated posh-git.

When I run into the issue, it causes my Powershell to fail (hang indefinitely) after any command. The only way I've found to recover is to rename my Powershell profile (causing it to be disabled), start Powershell (maybe even as non-admin), and then restore my profile.

As I mention in the answer to the question, the issue appears to have been fixed for posh-git, likely in [this commit](/dahlbyk/posh-git/commit/02a3d8809f4b379e3a68d667248e620dbdb0c98a).

I would be very interested in getting this fix applied to posh-hg as well. I'd gladly help incentivize a fix if I can. Just let me know you're interested and capable of solving the issue and I'll create a bountysource bounty.

**Comment by JeremySkinner** [comment]
I'm not actually actively developing posh-hg anymore, but I'm happy to make the same change that was in the commit you linked to. I'l ltry and get around to it either today or tomorrow.

**Comment by JeremySkinner** [comment]
I've made the change referenced in the posh-git commit. Please give it a try and let me know if it makes a difference

**Comment by jaraco** [comment]
Awesome. I've pulled the changes and merged them with my own fork and updated my environment. Because it's an intermittent issue, I won't know for a few weeks if it has worked.

So for now, let's assume it has worked, and if it has not, then I will re-open the ticket.
